# Settings
url: https://lufevida.github.io
baseurl: /html5up-lens
title: Lens
tagline: Just another fine responsive site template by HTML5 UP
copyright: Untitled

# Contact
twitter: username
facebook: username
instagram: username